# Generated by Django 3.1.8 on 2021-05-07 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.TextField()),
                ('mname', models.TextField()),
                ('lname', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('phoneNum', models.TextField()),
                ('address', models.TextField()),
                ('timeSlot', models.IntegerField(default=-1)),
                ('nPatients', models.IntegerField(default=0)),
                ('account', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('ssn', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.TextField()),
                ('mname', models.TextField()),
                ('lname', models.TextField()),
                ('firstDose', models.TextField(default='none')),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('race', models.TextField()),
                ('occupation', models.TextField()),
                ('email', models.EmailField(max_length=200)),
                ('address', models.TextField()),
                ('phoneNum', models.TextField()),
                ('medHistory', models.TextField()),
                ('account', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('hour', models.IntegerField(primary_key=True, serialize=False)),
                ('nNurses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('company', models.TextField()),
                ('desc', models.TextField()),
                ('requiredDoses', models.IntegerField(default=1)),
                ('dosesTotal', models.IntegerField()),
                ('dosesOnHold', models.IntegerField()),
                ('dosesAvailible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination_Record',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('nurse', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='covid.nurse')),
                ('patient', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='covid.patient')),
                ('vaccine', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='covid.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timeSlot', models.TextField(default='10am')),
                ('date', models.TextField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covid.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covid.patient')),
                ('vaccination', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='covid.vaccine')),
            ],
        ),
    ]
